### ISSUE TITLE
Add difficulty in topic command

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/DDoL#46]
The topic command can be merged into the random command by introducing a topic option in the random slash command, similar to the difficulty option.

I am suggesting this because both commands core functionality is same i.e giving random problem

**Comment by adarsh-site** [comment]
Instead of this we can enhance the topic command by adding easy, medium, and hard options. This will serve both purposes. If someone wants a random question, they can use the random command. If someone wants an easy, medium, hard or just a random question from a specific topic, they can use the topic command.

**Comment by rishabh7923** [comment]
Yea I suppose we can do this also.
I am thinking of replacing buttons in topics command with select menu

**Comment by adarsh-site** [comment]
select menu is a nice idea but buttons are more easy to navigate to.

**Comment by rishabh7923** [comment]
True but with select menu we can add functionality to select more than one topic which i think is quite a good feature.
But If you want buttons then lets just go with buttons

**Comment by adarsh-site** [comment]
update the issue title as: Add difficulty in topic command

**Comment by rishabh7923** [comment]
Done
